[build-system]
requires = [
    "setuptools>-42",
    "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
    | \.git
    | \.pytest_cache
  )/
)
'''