name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pipenv
      run: pip install pipenv
    - name: Run tests
      run: |
        pipenv install --dev
        pipenv run pytest
    - name: Lint With Black
      run: |
        pipenv run check-format
    - name: Run EDI CLI
      run: |
        for f in demo-files/*; do
           cli -a $f 1> /dev/null
           cli -e $f 1> /dev/null
           cli -v $f 1> /dev/null
           cli -t $f 1> /dev/null
           cli -e -v -t -p $f 1> /dev/null
           cli -p $f 1> /dev/null
        done